## TARGET-GUIDED ORDINAL ENCODING

Target-Guided Ordinal Encoding is a technique used to encode categorical variables based on their **relationship with the target variable**.

### Definition
This encoding method is especially useful when:
- A categorical feature has a **large number of unique categories**
- The feature has a **strong influence on the target variable**

Instead of assigning arbitrary numbers, categories are encoded using **statistics derived from the target variable**.

---

### How It Works
In Target-Guided Ordinal Encoding:
- Each category is replaced with the **mean or median of the target variable**
- Categories are then ordered based on these target statistics
- This creates a **monotonic relationship** between the encoded feature and the target

---

### Example (Conceptual)

| Category | Mean Target Value | Encoded Value |
|---------|------------------|---------------|
| A       | 200              | 3 |
| B       | 150              | 2 |
| C       | 80               | 1 |

---

### Key Points
- Uses **target information** for encoding  
- Handles **high-cardinality categorical variables** efficiently  
- Can improve **predictive performance**  
- Risk of **data leakage** if not applied correctly  
- Should be fitted **only on training data**

In [3]:
import pandas as pd

## Create a sample dataframe with ctaegorical variable and a target variable
df = pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price': [200,150,300,250,180,320]
})

In [4]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [6]:
df.groupby('city')['price'].mean()

city
London      150.0
New York    190.0
Paris       310.0
Tokyo       250.0
Name: price, dtype: float64

In [11]:
mean_price = df.groupby('city')['price'].mean().to_dict()
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [12]:
df['city_encoded'] = df['city'].map(mean_price)

In [13]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

## ASSIGNMENT

In [27]:
import seaborn as sns
data = sns.load_dataset('tips')
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [28]:
data.groupby('time')['total_bill'].mean()

C:\Users\ANKIT\AppData\Local\Temp\ipykernel_6884\3782284563.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby('time')['total_bill'].mean()

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [32]:
mean_total_bill = data.groupby('time')['total_bill'].mean().to_dict()
mean_total_bill

C:\Users\ANKIT\AppData\Local\Temp\ipykernel_6884\2016337223.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_total_bill = data.groupby('time')['total_bill'].mean().to_dict()

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [36]:
data['time_encode'] = data['time'].map(mean_total_bill)
data[['total_bill','time_encode']]

     total_bill time_encode
0         16.99   20.797159
1         10.34   20.797159
2         21.01   20.797159
3         23.68   20.797159
4         24.59   20.797159
..          ...         ...
239       29.03   20.797159
240       27.18   20.797159
241       22.67   20.797159
242       17.82   20.797159
243       18.78   20.797159

[244 rows x 2 columns]